<?php $presets["skin01r"] = array (
  'preset' => 'skin01r',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin17r.header-logo-regular.png?w=41&h=64',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin17r.header-logo-hd.png?w=82&h=128',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin01r.bottom-bar-logo-regular.png?w=25&h=40',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin01r.bottom-bar-logo-hd.png?w=50&h=80',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin17b.general-floating-menu-logo-regular.png?w=25&h=40',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin17r.general-floating-menu-logo-hd.png?w=50&h=80',
    1 => 0,
  ),
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-content_width' => '1250px',
  'general-layout' => 'wide',
  'general-box_width' => '1280px',
  'general-boxed_bg_color' => '#ffffff',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin17r.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'left',
  'general-show_breadcrumbs' => '1',
  'general-responsive' => '1',
  'general-accent_bg_color' => '#0fbcf5',
  'general-border_radius' => 4,
  'general-show_rel_posts' => '1',
  'general-rel_posts_head_title' => 'Related posts',
  'general-rel_posts_max' => 6,
  'general-smooth_scroll' => 'off',
  'fonts-font_family' => 'Roboto',
  'fonts-normal_size' => 14,
  'fonts-normal_size_line_height' => 25,
  'fonts-small_size' => 13,
  'fonts-small_size_line_height' => 23,
  'fonts-big_size' => 16,
  'fonts-big_size_line_height' => 27,
  'fonts-h1_font_family' => 'Roboto',
  'fonts-h1_font_size' => 46,
  'fonts-h1_line_height' => 52,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Roboto',
  'fonts-h2_font_size' => 36,
  'fonts-h2_line_height' => 42,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Roboto',
  'fonts-h3_font_size' => 26,
  'fonts-h3_line_height' => 34,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Roboto',
  'fonts-h4_font_size' => 20,
  'fonts-h4_line_height' => 28,
  'fonts-h4_uppercase' => false,
  'fonts-h5_font_family' => 'Roboto',
  'fonts-h5_font_size' => 18,
  'fonts-h5_line_height' => 27,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Roboto:400italic',
  'fonts-h6_font_size' => 15,
  'fonts-h6_line_height' => 24,
  'fonts-h6_uppercase' => false,
  'buttons-s_font_family' => 'Roboto:500',
  'buttons-s_font_size' => 14,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 31,
  'buttons-m_font_family' => 'Roboto',
  'buttons-m_font_size' => 16,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 40,
  'buttons-l_font_family' => 'Roboto',
  'buttons-l_font_size' => 18,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 48,
  'top_bar-bg_color' => '#eaeaea',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#3a3a3a',
  'header-bg_color' => '#ffffff',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#ffffff',
  'header-transparent_bg_opacity' => 100,
  'header-bg_height' => 60,
  'header-layout' => 'left',
  'header-show_floating_menu' => '1',
  'content-headers_color' => '#333333',
  'content-primary_text_color' => '#777777',
  'stripes-stripe_1_color' => '#fafafa',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#333333',
  'stripes-stripe_1_text_color' => '#777777',
  'stripes-stripe_2_color' => '#222222',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#f9f9f9',
  'stripes-stripe_2_text_color' => '#f9f9f9',
  'stripes-stripe_3_color' => '#c0f1fe',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin17r.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#2f363d',
  'stripes-stripe_3_text_color' => '#2f363d',
  'sidebar-bg_color' => '#fafafa',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-headers_color' => '#333333',
  'sidebar-primary_text_color' => '#777777',
  'footer-bg_color' => '#f6f6f6',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-headers_color' => '#333333',
  'footer-primary_text_color' => '#777777',
  'bottom_bar-bg_color' => '#3d80dc',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#777777',
  'bottom_bar-credits' => '1',
  'top_bar-font_size' => 'normal',
  'top_bar-bg_mode' => 'fullwidth_line',
  'menu-font_family' => 'Roboto:500',
  'menu-font_size' => 17,
  'menu-font_uppercase' => '1',
  'menu-next_level_indicator' => false,
  'menu-font_color' => '#3a3a3a',
  'menu-hover_font_color_mode' => 'color',
  'menu-hover_font_color' => '#3a3a3a',
  'menu-hover_font_color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#0ce6ab',
  ),
  'menu-decoration_style' => 'underline',
  'menu-hover_decoration_color_mode' => 'accent',
  'menu-hover_decoration_color' => '#a7e673',
  'menu-hover_decoration_color_gradient' => 
  array (
    0 => '#eeee22',
    1 => '#0bed56',
  ),
  'top_bar-paddings' => 7,
  'menu-iconfont_size' => 14,
  'menu-items_distance' => 26,
  'submenu-font_family' => 'Roboto:500',
  'submenu-font_size' => 12,
  'submenu-font_uppercase' => '1',
  'submenu-next_level_indicator' => '1',
  'submenu-font_color' => '#3a3a3a',
  'submenu-hover_font_color_mode' => 'accent',
  'submenu-hover_font_color' => '#895cb8',
  'submenu-hover_font_color_gradient' => 
  array (
    0 => '#81d742',
    1 => '#eeee22',
  ),
  'submenu-iconfont_size' => 12,
  'submenu-items_distance' => 18,
  'submenu-bg_color' => '#ffffff',
  'submenu-bg_opacity' => 97,
  'submenu-bg_width' => 250,
  'general-accent_color_mode' => 'gradient',
  'general-accent_bg_color_gradient' => 
  array (
    0 => '#4d71da',
    1 => '#35c4f4',
  ),
  'header-left_layout_elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'email',
      1 => 'phone',
      2 => 'skype',
    ),
    'top_bar_right' => 
    array (
      0 => 'cart',
      1 => 'login',
      2 => 'social_icons',
    ),
    'nav_area' => 
    array (
      0 => 'search',
    ),
  ),
  'header-center_layout_elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'email',
      1 => 'phone',
      2 => 'skype',
    ),
    'nav_area' => 
    array (
      0 => 'social_icons',
      1 => 'cart',
      2 => 'search',
    ),
  ),
  'header-near_logo_font_size' => 'big',
  'header-near_logo_bg_color' => '#9e9e9e',
  'header-classic_layout_elements' => 
  array (
    'logo_area' => 
    array (
      0 => 'address',
      1 => 'phone',
      2 => 'social_icons',
    ),
    'nav_area' => 
    array (
      0 => 'search',
      1 => 'cart',
    ),
  ),
  'header-side_paddings' => 40,
  'header-side_position' => 'left',
  'header-side_menu_align' => 'left',
  'header-side_layout_elements' => 
  array (
    'top' => 
    array (
      0 => 'phone',
      1 => 'custom_menu',
    ),
    'bottom' => 
    array (
      0 => 'social_icons',
      1 => 'text_area',
      2 => 'cart',
      3 => 'search',
    ),
  ),
  'header-woocommerce_cart_icon' => '1',
  'header-search_caption' => '',
  'header-left_layout_fullwidth' => false,
  'header-woocommerce_cart_caption' => 'Cart',
  'header-woocommerce_counter_bg_mode' => 'accent',
  'header-woocommerce_counter_bg_color' => '#6aa1ec',
  'header-woocommerce_counter_bg_color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#81d742',
  ),
  'header-login_caption' => 'Login',
  'header-soc_icon_color' => '#3a3a3a',
  'header-soc_icon_hover_color' => '#ffffff',
  'header-logo_padding_top' => '32',
  'header-logo_padding_bottom' => '32',
  'float_menu-height' => 70,
  'float_menu-transparency' => 100,
  'header-side_menu_width' => '280px',
  'header-side_menu_lines' => '0',
  'header-side_menu_lines_color' => '#eeeeee',
  'header-classic_menu_bg_mode' => 'fullwidth_line',
  'header-classic_menu_bg_color' => '#dcdcdc',
  'header-center_menu_bg_mode' => 'content_line',
  'header-center_menu_bg_color' => '#ededed',
  'header-soc_icon_bg_color_mode' => 'disabled',
  'header-soc_icon_bg_color' => '#ededed',
  'header-soc_icon_bg_color_gradient' => 
  array (
    0 => '#8224e3',
    1 => '#43d8c7',
  ),
  'header-soc_icon_hover_bg_color_mode' => 'accent',
  'header-soc_icon_hover_bg_color' => '#ededed',
  'header-soc_icon_hover_bg_color_gradient' => 
  array (
    0 => '#ef5689',
    1 => '#a6ff16',
  ),
  'general-title_size' => 'h3',
  'general-title_height' => 106,
  'general-title_bg_mode' => 'transparent_bg',
  'general-title_bg_color' => '#fafafa',
  'general-breadcrumbs_color' => '#aaaaaa',
  'general-breadcrumbs_bg_color' => 'disabled',
  'general-title_bg_image' => 
  array (
    'image' => '/images/backgrounds/patterns/full/brickwall.gif',
    'repeat' => 'no-repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'general-title_bg_fullscreen' => false,
  'general-title_bg_fixed' => false,
  'general-title_bg_parallax' => '',
  'buttons-style' => 'material',
  'buttons-color_mode' => 'accent',
  'buttons-color' => '#81d742',
  'buttons-color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#3a892a',
  ),
  'buttons-s_border_radius' => 4,
  'buttons-m_border_radius' => 4,
  'buttons-l_border_radius' => 4,
  'general-style' => 'ios7',
  'general-title_color' => '#333333',
  'image_hover-style' => 'blur',
  'image_hover-color_mode' => 'gradient',
  'image_hover-color' => '#000000',
  'image_hover-color_gradient' => 
  array (
    0 => '#355fbe',
    1 => '#35c4f4',
  ),
  'image_hover-opacity' => 30,
  'image_hover-with_icons_opacity' => 85,
  'general-next_prev_in_album' => '1',
  'general-show_back_button_in_album' => '1',
  'general-album_back_button_target_page_id' => 16237,
  'general-album_meta_on' => '1',
  'general-album_meta_date' => '1',
  'general-album_meta_author' => false,
  'general-album_meta_categories' => '1',
  'general-album_meta_comments' => false,
  'general-boxed_bg_fixed' => '1',
  'sidebar-width' => 26,
  'sidebar-vertical_distance' => 50,
  'sidebar-divider-vertical' => '1',
  'sidebar-divider-horizontal' => '0',
  'header-mobile-first_switch-after' => 970,
  'header-mobile-first_switch-logo' => 'mobile',
  'header-mobile-second_switch-after' => 200,
  'header-mobile-second_switch-logo' => 'mobile',
  'header-mobile-menu_color' => 'accent',
  'header-mobile-menu_color-background' => '#f94dda',
  'header-mobile-menu_color-text' => '#000000',
  'general-mobile_logo-regular' => 
  array (
    0 => '/inc/presets/images/full/skin17b.general-mobile-logo-regular.png?w=41&h=64',
    1 => 0,
  ),
  'general-mobile_logo-hd' => 
  array (
    0 => '/inc/presets/images/full/skin17b.general-mobile-logo-hd.png?w=82&h=128',
    1 => 0,
  ),
  'general-mobile_logo-padding_top' => '25',
  'general-mobile_logo-padding_bottom' => '25',
  'footer-style' => 'transparent_bg_line',
  'footer-slide-out-mode' => '0',
  'footer-paddings-top-bottom' => 50,
  'footer-paddings-columns' => 22,
  'bottom_bar-style' => 'full_width_line',
  'footer-collapse_after' => 970,
  'header-background' => 'normal',
  'header-menu_text_color_mode' => 'light',
  'header-menu_hover_color_mode' => 'light',
  'header-menu_top_bar_color_mode' => 'light',
  'header-bg_opacity' => 100,
  'header-bg_fullscreen' => false,
  'header-bg_fixed' => false,
  'header-center_menu_bg_opacity' => 100,
  'header-classic_menu_bg_opacity' => 55,
  'header-side_menu_lines_opacity' => 100,
  'general-bg_fixed' => false,
  'header-style' => 'solid_background',
  'general-responsiveness-treshold' => 970,
  'header-side_menu_dropdown_style' => 'side',
  'header-decoration' => 'line',
  'header-decoration_color' => '#e9e9e9',
  'sidebar-visual_style' => 'with_dividers',
  'header-floating_menu_animation' => 'fade',
  'header-mobile-top_bar_position' => 'closed',
  'float_menu-bg_color_mode' => 'header_color',
  'float_menu-bg_color' => '#ffffff',
  'header-side_menu_visibility' => 'always_visible',
  'header-logout_caption' => 'Logout',
  'header-left_layout_elements_visibility' => 'show',
  'header-center_layout_elements_visibility' => 'show',
  'header-classic_layout_elements_visibility' => 'show',
  'header-side_layout_elements_visibility' => 'show',
  'image_hover-default_icon' => 'white_icon',
  'general-content_boxes_bg_mode' => 'transparent',
  'general-content_boxes_solid_bg_color' => '#ffffff',
  'general-icons_style' => 'bold',
  'stripes-stripe_1_content_boxes_bg_mode' => 'transparent',
  'stripes-stripe_1_content_boxes_solid_bg_color' => '#ffffff',
  'stripes-stripe_2_content_boxes_bg_mode' => 'transparent',
  'stripes-stripe_2_content_boxes_solid_bg_color' => '#ffffff',
  'stripes-stripe_3_content_boxes_bg_mode' => 'transparent',
  'stripes-stripe_3_content_boxes_solid_bg_color' => '#ffffff',
  'general-title_bg_gradient' => 
  array (
    0 => '#4a66d6',
    1 => '#12b4ea',
  ),
  'header-woocommerce_show_cart_subtotal' => '1',
  'header-woocommerce_show_counter' => 'allways',
  'header-woocommerce_counter_color' => '#ffffff',
  'social_buttons-visibility' => 'allways',
); ?>